/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho2;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme Rissato
 */
public class frmMapa extends javax.swing.JFrame {
DefaultListModel listMochila = new DefaultListModel();
DefaultListModel listCinto = new DefaultListModel() ;
DefaultListModel listInfo = new DefaultListModel();
    /**
     * Creates new form frmMapa
     */
    public frmMapa() {
        initComponents();
        Trabalho2.inic.mapa();
        lblNivel.setText(Trabalho2.inic.nivelFrm);
        lblNomeHeroi.setText(Trabalho2.inic.vetHeroi.get(0).nome);
        lblVida.setText("Vida: " + String.valueOf(Trabalho2.inic.vetHeroi.get(0).vida));
        lstMochila.setModel(listMochila);
        
//      push na mochila dos items iniciais
        Trabalho2.inic.pushMochila(Trabalho2.inic.vetPocoes.get(0).nome);
        Trabalho2.inic.pushMochila(Trabalho2.inic.vetPocoes.get(2).nome);
//      coloca na lista o ultimo item 
        
            listMochila.addElement(Trabalho2.inic.mochila.peek());
        
//      coloca na mao a arma inicial(adaga)
        lblArma.setText(Trabalho2.inic.vetArmas.get(1).nome);
        lblDano.setText("- Dano: " + Trabalho2.inic.vetArmas.get(1).ataque);
 
        lblTipoNivel.setText(Trabalho2.inic.tipoNivel);
        
 
        if(null != lblTipoNivel.getText())
        switch (lblTipoNivel.getText()) {
            case "Nivel Inimigo":
                lstInfo.setModel(listInfo);
                listInfo.addElement("Nome do Inimigo: " + Trabalho2.inic.vetInfoI[0]);
                listInfo.addElement("Vida do Inimigo: " + Trabalho2.inic.vetInfoI[1]);
                listInfo.addElement("Força do Inimigo: " + Trabalho2.inic.vetInfoI[2]);
                lblItems.setText(Trabalho2.inic.inimigoItem);
                btnAtacar.setEnabled(true);
                btnTerminarNivel.setEnabled(false);
               
                
                
                break;
            case "Nivel Vazio":
                lstInfo.setModel(listInfo);
                lblItems.setText("");
                listInfo.addElement("Nesse nível você pode arrumar sua mochila e seus items");
                btnAddMochila.setEnabled(true);
                btnAddCinto.setEnabled(true);
                btnTerminarNivel.setEnabled(true);
                break;
            case "Nivel Elementos":
                lstInfo.setModel(listInfo);
                listInfo.addElement("Arma: " + Trabalho2.inic.vetInfoE[0]);
                listInfo.addElement("   Ataque: " + Trabalho2.inic.vetInfoE[1]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[2]);
                listInfo.addElement("Poção: " + Trabalho2.inic.vetInfoE[3]);
                listInfo.addElement("   Capacidade de cura: " + Trabalho2.inic.vetInfoE[4]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[5]);
                lblItems.setText(Trabalho2.inic.inimigoItem);
                btnAddMochila.setEnabled(true);
                btnAddCinto.setEnabled(true);
                btnTerminarNivel.setEnabled(true);
                break;
        }
        
    setDefaultCloseOperation(frmMenu.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNivel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMochila = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        lblNomeHeroi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCinto = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblTipoNivel = new javax.swing.JLabel();
        btnProximoNivel = new javax.swing.JButton();
        btnAddMochila = new javax.swing.JButton();
        btnAddCinto = new javax.swing.JButton();
        lblVida = new javax.swing.JLabel();
        lblArma = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstInfo = new javax.swing.JList<>();
        lblItems = new javax.swing.JLabel();
        btnTerminarNivel = new javax.swing.JButton();
        btnAtacar = new javax.swing.JButton();
        lblDano = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNivel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNivel.setText("Nivel");

        jScrollPane1.setViewportView(lstMochila);

        jLabel2.setText("Mochila:");

        lblNomeHeroi.setText("Nome Heroi");

        lstCinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCintoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstCinto);

        jLabel1.setText("Cinto:");

        lblTipoNivel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTipoNivel.setText("Tipo Do Nivel");

        btnProximoNivel.setText("Proximo Nivel");
        btnProximoNivel.setEnabled(false);
        btnProximoNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoNivelActionPerformed(evt);
            }
        });

        btnAddMochila.setText("Adicionar na mochila");
        btnAddMochila.setEnabled(false);
        btnAddMochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMochilaActionPerformed(evt);
            }
        });

        btnAddCinto.setText("Adicionar no cinto");
        btnAddCinto.setEnabled(false);

        lblVida.setText("Vida");

        lblArma.setText("Arma na Mao");

        lblInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblInfo.setText("Informarcao do nivel");

        jScrollPane3.setViewportView(lstInfo);

        lblItems.setText("inimigo/Items");

        btnTerminarNivel.setText("Terminar Nivel");
        btnTerminarNivel.setEnabled(false);
        btnTerminarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarNivelActionPerformed(evt);
            }
        });

        btnAtacar.setText("Atacar");
        btnAtacar.setEnabled(false);
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });

        lblDano.setText("Dano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblArma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDano))
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(btnAddMochila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnAddCinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblNomeHeroi)
                        .addComponent(lblVida))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTipoNivel)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTerminarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProximoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblItems, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoNivel)
                        .addGap(18, 18, 18)
                        .addComponent(btnProximoNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminarNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblItems, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(lblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblNomeHeroi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArma)
                            .addComponent(lblDano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtacar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddCinto)
                            .addComponent(btnAddMochila))))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMochilaActionPerformed
        // TODO add your handling code here:
        lstInfo.getSelectedValue();
        if(Trabalho2.inic.vetInfoE[0] == null ||  Trabalho2.inic.vetInfoE[3] == null){
            listInfo.removeAllElements();
            btnAddMochila.setEnabled(false);
        
        }else if(lstInfo.getSelectedValue().equals("Arma: " + Trabalho2.inic.vetInfoE[0])){
           Trabalho2.inic.pushMochila(Trabalho2.inic.vetInfoE[0]);
           for(int i = 0 ; i<=2;i++){
           Trabalho2.inic.vetInfoE[i] = null;
           }
           listMochila.removeAllElements();
           listMochila.addElement(Trabalho2.inic.mochila.peek());
           listInfo.removeAllElements();
           if(Trabalho2.inic.vetInfoE[0] == null){
            listInfo.addElement("Poção: " + Trabalho2.inic.vetInfoE[3]);
                listInfo.addElement("   Capacidade de cura: " + Trabalho2.inic.vetInfoE[4]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[5]);
           }
           
                     
       }else if(lstInfo.getSelectedValue().equals("Poção: " + Trabalho2.inic.vetInfoE[3])){
           Trabalho2.inic.pushMochila(Trabalho2.inic.vetInfoE[3]);
           for(int j = 3 ; j<=5;j++){
           Trabalho2.inic.vetInfoE[j] = null;
           }
           listMochila.removeAllElements();
           listMochila.addElement(Trabalho2.inic.mochila.peek());
           listInfo.removeAllElements();
           if(Trabalho2.inic.vetInfoE[3] == null){
           listInfo.addElement("Arma: " + Trabalho2.inic.vetInfoE[0]);
                listInfo.addElement("   Ataque: " + Trabalho2.inic.vetInfoE[1]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[2]);
           }
           
       
       }else if(lstInfo.getSelectedValue() != "Poção: " + Trabalho2.inic.vetInfoE[3] && lstInfo.getSelectedValue() != "Arma: " + Trabalho2.inic.vetInfoE[0] ){
           JOptionPane.showMessageDialog(null, "Você só pode colocar o item na mochila ou no cinto se clicar no nome dele antes");
      
       }
        
    }//GEN-LAST:event_btnAddMochilaActionPerformed

    private void lstCintoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCintoMouseClicked
        // TODO add your handling code here:
        lblArma.setText(lstCinto.getSelectedValue());
    }//GEN-LAST:event_lstCintoMouseClicked

    private void btnProximoNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoNivelActionPerformed
        // TODO add your handling code here:
        listInfo.removeAllElements();
        listMochila.removeAllElements();
        listCinto.removeAllElements();
        Trabalho2.inic.mapa();
        lblNivel.setText(Trabalho2.inic.nivelFrm);
         lblVida.setText("vida: " + String.valueOf(Trabalho2.inic.vetHeroi.get(0).vida));
//        mostra o ultimo item colcado da mochila 
            listMochila.addElement(Trabalho2.inic.mochila.peek());
        
         
        lblTipoNivel.setText(Trabalho2.inic.tipoNivel);
         
         if(null != lblTipoNivel.getText())
        switch (lblTipoNivel.getText()) {
            case "Nivel Inimigo":
                lstInfo.setModel(listInfo);
                listInfo.addElement("Nome do Inimigo: " + Trabalho2.inic.vetInfoI[0]);
                listInfo.addElement("   Vida do Inimigo: " + Trabalho2.inic.vetInfoI[1]);
                listInfo.addElement("   Força do Inimigo: " + Trabalho2.inic.vetInfoI[2]);
                lblItems.setText(Trabalho2.inic.inimigoItem);
                btnAtacar.setEnabled(true);
                btnTerminarNivel.setEnabled(false);
                break;
            case "Nivel Vazio":
                lstInfo.setModel(listInfo);
                lblItems.setText("");
                listInfo.addElement("Nesse nível você pode arrumar sua mochila e seus items");
                btnAddMochila.setEnabled(true);
                btnAddCinto.setEnabled(true);
                btnTerminarNivel.setEnabled(true);
                break;
            case "Nivel Elementos":
                lstInfo.setModel(listInfo);
                listInfo.addElement("Arma: " + Trabalho2.inic.vetInfoE[0]);
                listInfo.addElement("   Ataque: " + Trabalho2.inic.vetInfoE[1]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[2]);
                listInfo.addElement("Poção: " + Trabalho2.inic.vetInfoE[3]);
                listInfo.addElement("   Capacidade de cura: " + Trabalho2.inic.vetInfoE[4]);
                listInfo.addElement("   Peso: " + Trabalho2.inic.vetInfoE[5]);
                lblItems.setText(Trabalho2.inic.inimigoItem);
                btnAddMochila.setEnabled(true);
                btnAddCinto.setEnabled(true);
                btnTerminarNivel.setEnabled(true);
                break;
    }
         btnProximoNivel.setEnabled(false);
    }//GEN-LAST:event_btnProximoNivelActionPerformed

    private void btnTerminarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarNivelActionPerformed
        // TODO add your handling code here:
        btnProximoNivel.setEnabled(true);
        btnAtacar.setEnabled(false);
        btnTerminarNivel.setEnabled(false);
        btnAddMochila.setEnabled(false);
        btnAddCinto.setEnabled(false);
        
    }//GEN-LAST:event_btnTerminarNivelActionPerformed

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i <Trabalho2.inic.vetArmas.size();i++ ){
            if(Double.valueOf(Trabalho2.inic.vetInfoI[1]) <= 0){
                btnAtacar.setEnabled(false);
                listInfo.removeAllElements();
                Trabalho2.inic.vetInfoI[1] = "0";
                lstInfo.setModel(listInfo);
                listInfo.addElement("Nome do Inimigo: " + Trabalho2.inic.vetInfoI[0]);
                listInfo.addElement("   Vida do Inimigo: " + Trabalho2.inic.vetInfoI[1]);
                listInfo.addElement("   Força do Inimigo: " + Trabalho2.inic.vetInfoI[2]);
                btnTerminarNivel.setEnabled(true);
            }
        if(lblArma.getText().equals(Trabalho2.inic.vetArmas.get(i).nome)){
            
//          atualizando a vida do inimigo
            Double vida = Double.valueOf(Trabalho2.inic.vetInfoI[1]);
            vida = vida - Trabalho2.inic.vetArmas.get(i).ataque;
            Trabalho2.inic.vetInfoI[1] = String.valueOf(vida);
             listInfo.removeAllElements();
                lstInfo.setModel(listInfo);
                listInfo.addElement("Nome do Inimigo: " + Trabalho2.inic.vetInfoI[0]);
                listInfo.addElement("   Vida do Inimigo: " + Trabalho2.inic.vetInfoI[1]);
                listInfo.addElement("   Força do Inimigo: " + Trabalho2.inic.vetInfoI[2]);
//            atualizando a vida do heroi
            Double vidaHeroi;
            vidaHeroi = Trabalho2.inic.vetHeroi.get(0).vida;
             vidaHeroi = vidaHeroi - Double.valueOf(Trabalho2.inic.vetInfoI[2]);
            Trabalho2.inic.vetHeroi.get(0).vida = vidaHeroi;
            lblVida.setText("Vida: " + Trabalho2.inic.vetHeroi.get(0).vida);
                
        }
        }
    }//GEN-LAST:event_btnAtacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMapa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCinto;
    private javax.swing.JButton btnAddMochila;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnProximoNivel;
    private javax.swing.JButton btnTerminarNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArma;
    private javax.swing.JLabel lblDano;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNomeHeroi;
    private javax.swing.JLabel lblTipoNivel;
    private javax.swing.JLabel lblVida;
    private javax.swing.JList<String> lstCinto;
    private javax.swing.JList<String> lstInfo;
    private javax.swing.JList<String> lstMochila;
    // End of variables declaration//GEN-END:variables
}
